Make directory /etc/module-build-service instead of link
rhpkg could be installed inside Vagrant machine to run MBS with internal
infra. rhpkg installs config file into /etc/module-build-service, which
could fail with following error if /etc/module-build-service is a link
to /opt/module_build_service/conf.

error: unpacking of archive failed on file
/etc/module-build-service/redhat.py;5be25ac4: cpio: chown

Signed-off-by: Chenxiong Qi <cqi@redhat.com>